<div class="nav-home">
<a href="$page.home.href$" $if(page.home.active)$class="active"$endif$>
<span class="home-icon">⌂</span>$page.home.title$</a>
<!--<div class="version-number">
$page.properties.("project.version.short")$
</div>-->
</div>
$groups()$
<div class="nav-toc">
$page.navigation$
<hr/>
<ul>
<li><a href="https://www.researchgate.net/profile/Helena_Edelson2"><img src="images/researchgate.png" style="padding-right:5px"/>researchgate</a></li>
<li><a href="https://twitter.com/helenaedelson"><img src="images/twitter.png"/>@helenaedelson</a></li>
<li><a href="https://github.com/helena"><img src="images/octocat.jpg"  style="padding-right:5px"/>github/helena</a></li>
<li><a href="https://linkedin.com/in/helenaedelson"><img src="images/linkedin2.png" style="padding-right:5px"/>linkedin/helena</a></li>
</ul>
<br/>
</div>
